### 1. Создание пользователя
POST http://localhost:8080/user
Content-Type: application/json

{
  "nickName": "Veles",
  "name": "Maks",
  "email": "veless@gmail.com"
}

### 2. Редактирование пользователя с id: 5
PUT http://localhost:8080/user/5
Content-Type: application/json

{
"nickName": "Veless",
"name": "David",
"email": "davidd@gmail.com"
}

### 3. Создание канала
POST http://localhost:8080/channel?authorId=5
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="ufc.jpg"
Content-Type: image/jpeg

#(data)

--WebKitFormBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
    "name": "Ufc",
    "language": "ru",
    "category": "battle",
    "shortDescription": "Ufc fights"
}
--WebKitFormBoundary

### 4. Редактирование канала
PUT http://localhost:8080/channel?channelId=6
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Type: image/jpg
Content-Disposition: form-data; name="file"; filename="ufc.jpg"


(data)
--WebKitFormBoundary
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
      "name": "Jetix",
      "language": "Russian",
      "shortDescription": "vse dlya malishei",
      "category": "Kids"
    }
--WebKitFormBoundary

### 5. Подписка пользователя на канал
PUT http://localhost:8080/channel/subscribe?channelId=7&personId=2

### 6. Отписка пользователя с канала
PUT http://localhost:8080/channel/unsubscribe?channelId=7&personId=2

## 7. Отображение списка всех каналов с пагинацией и фильтрацией по языку/категории/названию
### 7 Фильтр по названию, языку и категории + пагинация
GET http://localhost:8080/channel/filter?language=ru&name=trav&category=trav&page=0&size=2
### 7.1 Фильтр по языку + пагинация(опционально)
GET http://localhost:8080/channel/filter?language=rus&page=0&size=2
### 7.2 Фильтр по названию + пагинация(опционально)
GET http://localhost:8080/channel/filter?name=fin&page=0&size=2
### 7.3 Фильтр по категории + пагинация(опционально)
GET http://localhost:8080/channel/filter?category=trav&page=0&size=2

### 8. Отображение списка всех подписок пользователя(без пагинации, отображаются только имена каналов)
GET http://localhost:8080/user/subscriptions?personId=5

### 9. Получение подробной информации об канале(название, категория, ид, дата создания, кол-во подписчиков, автор, язык, обложка)
GET http://localhost:8080/channel/5

###